name = "work-ubq-fi"

compatibility_date = "2024-10-23"

pages_build_output_dir = "./static"

[[kv_namespaces]]
binding = "KVNamespace"
id = "0a6aaf0a6edb428189606b116da58ef7"

# These secrets need to be configured via Cloudflare dashboard:
# SUPABASE_URL = ""
# SUPABASE_ANON_KEY = ""

